---
- name: Example of using loop with conditional operator
  hosts: node4
  become: true
  gather_facts: false
  tasks:
    - name: loop runs for value is greater than 5
      ansible.builtin.command: echo {{ item }}
      loop: [ 0, 2, 4, 6, 8, 10 ]
      when: item > 5
...
