---
- name: delete partioion
  hosts: 192.168.159.135
  become: true
  tasks:
    - name: deleting partition /dev/nvme0n2p1
      parted:
        device: /dev/nvme0n2
        number: 1
        state: absent
...
