#SPDX-License-Identifier: MIT-0
---
# handlers file for apache
- name: restart apache
  service:
    name: "{{ name }}"
    state: "{{ res }}"
    enabled: "{{ enabled }}"

- name: reload firewalld
  service:
    name: "{{ s_name }}"
    state: "{{ s_state }}"
