---
- name: Example of adding Ethernet connection and static ip usinf nmcli module
  hosts: node4
  become: true
  tasks:
    - name: adding ethernet connection and assigning static ip
      community.general.nmcli:
        conn_name: ens256
        ifname: ens256
        type: ethernet
        ip4: 192.168.159.152/24
        gw4: 192.168.159.1
        dns4: 8.8.8.8
        state: present
        autoconnect: true
...
