---
- name: Example of modifying existing connection 1) adding two more ip in connection using nmcli module
  hosts: node4
  become: true
  tasks:
    - name: modifying existing connection and adding two IPs
      community.general.nmcli:
        conn_name: ens256
        ifname: ens256
        type: ethernet
        ip4:
          - 192.168.159.140/24
          - 192.168.159.141/24
          - 192.168.159.142/24
        gw4: 192.168.159.1
        dns4:
          - 8.8.8.8
          - 192.168.159.128
        state: present
        autoconnect: true
...
