---
- name: Example of removing an existing connection using nmcli module
  hosts: node4
  become: true
  tasks:
    - name: removinng an existing connection
      community.general.nmcli:
        conn_name: ens256
        ifname: ens256
        type: ethernet
        ip4: 192.168.159.152/24
        gw4: 192.168.159.1
        state: absent
        autoconnect: true
...
