---
- name: Example of allowing udp 161 & 162 port in default zone & allow http service in dmz zone using firewalld module
  hosts: node4
  become: true
  tasks:
    - name: Allowing udp port 161 & 162
      ansible.posix.firewalld:
        port: 161-162/udp
        state: enabled
        permanent: true
        immediate: yes
    - name: allowing http service in dmz zone
      ansible.posix.firewalld:
        zone: dmz
        service: http
        state: enabled
        permanent: true
        immediate: yes
...  
