---
- name: Example of configurint SMTP mail server using ansible playbook
  hosts: node4
  become: true
  tasks:
    - name: Setting hostname on managed node
      hostname:
        name: mail-server.devops.local
        use: systemd
    - name: Installing sendmail packaged in machine
      package:
        name:
          - sendmail*
          - procmail
          - s-nail
          - make
        state: latest
    - name: Creating authinfo file in /etc/mail directory  containing authenticaion information
      template:
        src: /home/rohan/Playbooks/mail_server/authinfo.j2
        dest: /etc/mail/authinfo
    - name: Copying sendmail configuration file in /etc/mail directory by sendmail.mc name
      template:
        src: /home/rohan/Playbooks/mail_server/sendmail.mc.j2
        dest: /etc/mail/sendmail.mc
        force: true
    - name: making changes in sendmail.cf file using m4 processor with the help of sendmail.mc file
      shell: m4 /etc/mail/sendmail.mc > /etc/mail/sendmail.cf
    - name: Creating encrypted database file (authinfo.db) using autinfo file
      shell: make hash /etc/mail/authinfo < /etc/mail/autoinfo
    - name: Starting and enabling sendmail.service
      service:
        name: sendmail
        state: started
        enabled: true
...
