---
- name: example of installing package ghroup using yum module
  hosts: node4
  become: true
  tasks:
    - name: installing 'Devlopment tools' group packages
      yum:
        name: '@Development tools'
        state: present
...
