---
- name: Example of patching using yum module / example of updating all packages
  hosts: node4
  become: true
  tasks:
    - name: upgrading all packages
      yum:
        name: '*'
        state: latest
...
