---
- name: Example of patching except/excluding some packages
  hosts: node4
  become: true
  tasks:
    - name: Patching nodes excluding some packages
      dnf:
        name: '*'
        state: latest
        exclude: kernel*, chrony*
...
