---
- name: Example of remove repository using yum_repository module
  hosts: node4
  become: true
  tasks:
    - name: removing reposiroty
      yum_repository:
        name: epel
        state: absent
...
