---
- name: Example creating rpository using yum_repository module
  hosts: node4
  become: true
  tasks:
    - name: Creating repository
      yum_repository:
        name: epel
        description: epel-repo
        baseurl: https://api.github.com/user/repos
...
