#SPDX-License-Identifier: MIT-0
---
# tasks file for apache
  vars_files:
    - vars/main.yaml
- name: Install apache2
  package:
    name: "{{ name }}"
    state: "{{ state }}"
  when: ansible_distribution == "{{ dist }}" 
