---
- name: Example of using block on only RedHat machine
  hosts: all
  gather_facts: true
  tasks:
    - block:
      - name: Installing httpd service
        package:
          name: httpd
          state: present

      - name: starting and enabling httpd service
        service:
          name: httpd
          state: started
      become: true
      when: ansible_facts.distribution == "RedHat"
...
