---
- name: Example of listing type variable
  hosts: node4
  become: true
  vars:
    mypkgs:
      - ftp
      - vsftpd
      - zsh
  tasks:
    - name: Installing the packages
      package:
        name: "{{ mypkgs }}"
        state: installed
...
