---
- name: Example of mapping or dicionary type variables
  hosts: node4
  become: true
  tasks:
    - name: Creating users on managed node
      user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        state: present
      loop:
        - name: demo1
          uid: 1020
        - name: demo2
          uid: 1030
        - name: dmeo3
          uid: 1040
...
